### ISSUE TITLE
Right click on project menu crash

### ISSUE THREAD

**Issue by triskator** [junichi11/netbeans-wordpress-plugin#49]
Hi, 
I've got this problem. Everytime I open PHP project, or have some already opened (PHP projects only, java works) I right click on project I get Exception from Netbeans and menu won't show.
I tracked it down to the plugin PHP WordPress Blog/CMS. I've got clean installation of NB 8.1 on windows 8.1 x64, recently reinstalled too. I have few plugins out of date, because they didn't pass verification on NB 8.1 yet, but I disabled all of them except this plugin and this seems to be source of problem. Any ideas? Btw restart of NB or Win not helping. 

Here is what NB spit off as Exception, if you need the rest from the Log, I can provide that too, Thank you..:

java.lang.IndexOutOfBoundsException: Index: 29, Size: 28
	at java.util.LinkedList.checkPositionIndex(LinkedList.java:560)
	at java.util.LinkedList.add(LinkedList.java:507)
	at org.netbeans.modules.php.project.ui.logicalview.PhpLogicalViewProvider$PhpLogicalViewRootNode.addFrameworks(PhpLogicalViewProvider.java:457)
	at org.netbeans.modules.php.project.ui.logicalview.PhpLogicalViewProvider$PhpLogicalViewRootNode.getActions(PhpLogicalViewProvider.java:381)
	at org.openide.nodes.FilterNode.getActions(FilterNode.java:751)
	at org.openide.nodes.NodeOp.findActions(NodeOp.java:162)
	at org.openide.explorer.view.TreeView.createPopup(TreeView.java:1056)
	at org.openide.explorer.view.TreeView$PopupAdapter.showPopup(TreeView.java:1555)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.maybePopup(MouseUtils.java:189)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.mouseReleased(MouseUtils.java:184)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by junichi11** [comment]
Probably, it's not this plugin's problem. 
Could you try to check whether your PHP modules are available?(Tools > Plugins) Thanks.

**Comment by triskator** [comment]
Damn it was disabled.. I guess it pops up whenever I want to activate module on New Project rather than on Open existing php project. So I presumed it was already running when everything else was working.. Thank you very much, it's working perfectly now.

**Comment by junichi11** [comment]
Thanks for your confirmation.

> it's working perfectly now.

:+1: 

AFAIR, it was already fixed in development version. Probably, the patch will be provided in next update.

**Comment by junichi11** [comment]
> it was already fixed in development version.

NOTE: This means that the Exception was fixed. In other words, php modules may be disabled by default yet.
